#########################
# d={'a':12,'b':213}
# print(d)
##print(d[0])
# print('d[\'a\']=',d['a'])
# a=int(input('input value you want in d[\'a\']:'))
# d['a']=a
# print('d[\'a\']=',d['a'])
# print('print(d):',d)
# print('d.get(\'b\')=',d.get('b'))
# print('d.get(\'c\')=',d.get('c'))
# print('d.get(\'c\',3333)=',d.get('c',3333))
# d.pop('a')
# print('d.pop(\'a\') print(d)',d)
#########################
# s=set(['a',2,3])
# print('set([\'a\',2,3])=',s)
# b=input('input value you want in s:')
# s.add(b)
# print('s.add(b):',s)
# s.add('v')
# print('s.add(\'v\'):',s)
# s.add('t')
# print('s.add(\'t\'):',s)
# s.add(-3)
# print('s.add(-3):',s)
# s.add(8)
# print('s.add(8):',s)
# s.remove('v')
# print('s.remove(\'v\'):',s)
# s={1,2,3,'a','b'}
# print('s={1,2,3,\'a\',\'b\'}:',s)
# a=input('a=input value u want in set:')
# b=input('b=input value u want in set:')
# c=input('c=input value u want in set:')
# t={a,b,c}
# print('t={a,b,c}:',t)
# print('s&t:',s&t)
# print('s|t:',s|t)
#########################
a=input('a=input the original str:')
b=a.replace('a','A')
print('b=a.replace(\'a\',\'A\')=',b)
print('a=',a)